language: generic
dist: bionic
cache: packages

install:
  # From https://tecadmin.net/install-go-on-ubuntu/
  - wget https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
  - sudo tar -xvf go1.12.7.linux-amd64.tar.gz
  - sudo mv go /usr/local
  - export GOROOT=/usr/local/go
  - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check

script:
  # Show Go's version
  - go version
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links
